<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup Label="Build">
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Marten" Version="8.17.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="Microsoft.SourceLink.GitHub" Version="8.0.0" />
    <PackageReference Update="MinVer" Version="6.1.0" />
  </ItemGroup>
</Project>
