
-- Generated by Sable on 7/26/2026 7:04:15 PM
-- Sable NoIdempotenceWrapper

CREATE SCHEMA IF NOT EXISTS schema_preamble_sample;

CREATE TABLE IF NOT EXISTS schema_preamble_sample.__sable_migrations (
    migration_id        character varying(150)      NOT NULL,
    date_applied        timestamp without time zone NOT NULL DEFAULT (now() at time zone 'utc'),
    backfilled          boolean                     NOT NULL DEFAULT false,
CONSTRAINT pkey___sable_migrations_migration_id PRIMARY KEY (migration_id)
);
