// Copyright 2024 Bloomberg Finance L.P.
// Distributed under the terms of the MIT license.

using Xunit;

namespace Sable.Cli.Tests;

public class MigrationTests : IDisposable
{
    private const string ExpectedUnsupportedMessage =
        "Sable cannot safely wrap migration '20260710000000_Test' because it begins with an unsupported top-level DO statement. Only a recognized safe schema-creation preamble can be moved outside the idempotence guard. Use Sable's no-idempotence workflow only when the migration is independently idempotent.";

    private readonly string _directory = Path.Combine(
        Path.GetTempPath(),
        $"sable-migration-tests-{Guid.NewGuid():N}"
    );

    [Fact]
    public void ConsecutiveSafeSchemaPreamblesAreHoistedBeforeTheGuard()
    {
        var migration = CreateMigration(
            """
            -- Generated by Sable

            DO $$
            BEGIN
                BEGIN
                    EXECUTE 'CREATE SCHEMA IF NOT EXISTS sample';
                EXCEPTION
                    WHEN duplicate_schema THEN NULL;
                    WHEN unique_violation THEN NULL;
                END;
            END
            $$;

            DO LANGUAGE plpgsql $schema$
            BEGIN
                BEGIN
                    EXECUTE 'CREATE SCHEMA IF NOT EXISTS sample';
                EXCEPTION
                    WHEN unique_violation THEN NULL;
                    WHEN duplicate_schema THEN NULL;
                END;
            END
            $schema$;

            CREATE OR REPLACE FUNCTION sample.answer() RETURNS integer LANGUAGE sql AS $$
                SELECT 42;
            $$;
            """
        );

        var script = migration.GetIdempotentScript();
        var guardIndex = script.IndexOf("DO $sable$", StringComparison.Ordinal);

        Assert.True(guardIndex >= 0);
        Assert.True(script.IndexOf("DO $$", StringComparison.Ordinal) < guardIndex);
        Assert.True(script.IndexOf("DO LANGUAGE plpgsql $schema$", StringComparison.Ordinal) < guardIndex);
        Assert.True(script.IndexOf("CREATE OR REPLACE FUNCTION", StringComparison.Ordinal) > guardIndex);
        Assert.Contains("AS $$", script);
    }

    [Fact]
    public void LegacyInformationSchemaPreambleIsHoistedBeforeTheGuard()
    {
        var migration = CreateMigration(
            """
            -- Generated by Sable

            DO $$
            BEGIN    IF NOT EXISTS(
                    SELECT schema_name
                      FROM information_schema.schemata
                      WHERE schema_name = 'sample'
                  )
                THEN
                  EXECUTE 'CREATE SCHEMA sample';
                END IF;

            END
            $$;

            DROP FUNCTION IF EXISTS sample.mt_upsert_item(jsonb) cascade;
            """
        );

        var script = migration.GetIdempotentScript();
        var guardIndex = script.IndexOf("DO $sable$", StringComparison.Ordinal);

        Assert.True(guardIndex >= 0);
        Assert.True(script.IndexOf("DO $$", StringComparison.Ordinal) < guardIndex);
        Assert.True(script.IndexOf("DROP FUNCTION", StringComparison.Ordinal) > guardIndex);
    }

    [Fact]
    public void LegacyTransactionEnvelopeIsRemovedBeforeComposition()
    {
        var migration = CreateMigration(
            """
            -- Generated by Sable

            DO LANGUAGE plpgsql $tran$
            BEGIN

            DO $$
            BEGIN
                IF NOT EXISTS(
                    SELECT schema_name FROM information_schema.schemata
                    WHERE schema_name = 'sample'
                )
                THEN
                    EXECUTE 'CREATE SCHEMA sample';
                END IF;
            END
            $$;

            CREATE TABLE sample.items (id uuid PRIMARY KEY);

            END;
            $tran$;
            """
        );

        var script = migration.GetIdempotentScript();
        var guardIndex = script.IndexOf("DO $sable$", StringComparison.Ordinal);

        Assert.DoesNotContain("$tran$", script);
        Assert.True(script.IndexOf("DO $$", StringComparison.Ordinal) < guardIndex);
        Assert.True(script.IndexOf("CREATE TABLE", StringComparison.Ordinal) > guardIndex);
    }

    [Fact]
    public void NoIdempotenceDirectiveKeepsTheOriginalScriptUnwrapped()
    {
        var migration = CreateMigration(
            """
            -- Generated by Sable
            -- Sable NoIdempotenceWrapper

            DO $$
            BEGIN
                BEGIN
                    EXECUTE 'CREATE SCHEMA IF NOT EXISTS sample';
                EXCEPTION
                    WHEN duplicate_schema THEN NULL;
                    WHEN unique_violation THEN NULL;
                END;
            END
            $$;

            CREATE INDEX CONCURRENTLY IF NOT EXISTS sample_index ON sample.items (id);
            """
        );

        var script = migration.GetIdempotentScript();

        Assert.DoesNotContain("RAISE NOTICE 'Running migration", script);
        Assert.Contains("RAISE NOTICE 'Inserting record for migration", script);
        Assert.True(
            script.IndexOf("CREATE INDEX CONCURRENTLY", StringComparison.Ordinal)
                < script.IndexOf("RAISE NOTICE 'Inserting record", StringComparison.Ordinal)
        );
    }

    [Fact]
    public void BothDirectivesRemainAuthoritativeForASafePreamble()
    {
        var migration = CreateMigration(
            """
            -- Sable NoIdempotenceWrapper
            -- Sable NoTransactionWrapper

            DO $$
            BEGIN
                BEGIN
                    EXECUTE 'CREATE SCHEMA IF NOT EXISTS sample';
                EXCEPTION
                    WHEN duplicate_schema THEN NULL;
                    WHEN unique_violation THEN NULL;
                END;
            END
            $$;
            """
        );

        var script = migration.GetTransactionalIdempotentScript();

        Assert.DoesNotContain("BEGIN;", script);
        Assert.DoesNotContain("RAISE NOTICE 'Running migration", script);
        Assert.Contains("RAISE NOTICE 'Inserting record for migration", script);
    }

    [Theory]
    [MemberData(nameof(UnsupportedTopLevelDoScripts))]
    public void UnsupportedTopLevelDoFailsClosed(string script)
    {
        var exception = Assert.Throws<InvalidOperationException>(() =>
            CreateMigration(script).GetIdempotentScript()
        );

        Assert.Equal(ExpectedUnsupportedMessage, exception.Message);
    }

    [Fact]
    public void OrdinaryMigrationRemainsInsideIdempotenceBlock()
    {
        var migration = CreateMigration("CREATE TABLE sample.items (id uuid PRIMARY KEY);");

        var script = migration.GetIdempotentScript();

        Assert.Contains("DO $sable$", script);
        Assert.Contains("RAISE NOTICE 'Running migration", script);
        Assert.DoesNotContain("RAISE NOTICE 'Inserting record for migration", script);
    }

    public static IEnumerable<object[]> UnsupportedTopLevelDoScripts()
    {
        yield return
        [
            """
            DO $$
            BEGIN
                NULL;
            END
            $$;
            """,
        ];
        yield return
        [
            """
            DO $$
            BEGIN
                RAISE NOTICE 'CREATE SCHEMA IF NOT EXISTS sample';
            END
            $$;
            """,
        ];
        yield return
        [
            """
            DO $$
            BEGIN
                -- CREATE SCHEMA IF NOT EXISTS sample;
                DELETE FROM sample.items;
            END
            $$;
            """,
        ];
        yield return
        [
            """
            DO $$
            BEGIN
                BEGIN
                    EXECUTE 'CREATE SCHEMA IF NOT EXISTS other_schema';
                EXCEPTION
                    WHEN duplicate_schema THEN NULL;
                    WHEN unique_violation THEN NULL;
                END;
            END
            $$;
            """,
        ];
        yield return
        [
            """
            DO $$
            BEGIN
                CREATE SCHEMA IF NOT EXISTS sample;
            END
            $$;
            """,
        ];
        yield return
        [
            """
            DO $$
            BEGIN
                BEGIN
                    EXECUTE 'CREATE SCHEMA IF NOT EXISTS sample';
                EXCEPTION
                    WHEN duplicate_schema THEN NULL;
                    WHEN unique_violation THEN NULL;
                END;
                DELETE FROM sample.items;
            END
            $$;
            """,
        ];
        yield return
        [
            """
            DO $$
            BEGIN
                BEGIN
                    EXECUTE 'CREATE SCHEMA IF NOT EXISTS sample';
                END;
            """,
        ];
        yield return
        [
            """
            DO $$
            BEGIN
                IF NOT EXISTS(
                    SELECT schema_name FROM information_schema.schemata
                    WHERE schema_name = 'other_schema'
                )
                THEN
                    EXECUTE 'CREATE SCHEMA sample';
                END IF;
            END
            $$;
            """,
        ];
        yield return
        [
            """
            DO $$
            BEGIN
                IF NOT EXISTS(
                    SELECT schema_name FROM information_schema.schemata
                    WHERE schema_name = 'sample' OR 1 = 1
                )
                THEN
                    EXECUTE 'CREATE SCHEMA sample';
                END IF;
            END
            $$;
            """,
        ];
        yield return
        [
            """
            DO $$
            BEGIN
                IF NOT EXISTS(
                    SELECT schema_name FROM information_schema.schemata
                    WHERE schema_name = 'sample'
                )
                THEN
                    EXECUTE 'CREATE SCHEMA sample';
                    DELETE FROM sample.items;
                END IF;
            END
            $$;
            """,
        ];
    }

    public void Dispose()
    {
        if (Directory.Exists(_directory))
        {
            Directory.Delete(_directory, true);
        }
    }

    private Migration CreateMigration(string script)
    {
        Directory.CreateDirectory(_directory);
        var filePath = Path.Combine(_directory, "20260710000000_Test.sql");
        File.WriteAllText(filePath, script);
        return new Migration(filePath, "sample");
    }
}
