// Copyright 2024 Bloomberg Finance L.P.
// Distributed under the terms of the MIT license.

using Xunit;

namespace Sable.Cli.Tests;

public class MigrationTests : IDisposable
{
    private readonly string _directory = Path.Combine(
        Path.GetTempPath(),
        $"sable-migration-tests-{Guid.NewGuid():N}"
    );

    [Fact]
    public void LeadingSchemaCreationBlockIsHoistedOutsideIdempotenceBlock()
    {
        var migration = CreateMigration(
            """
            -- Generated by Sable

            DO $$
            BEGIN
                CREATE SCHEMA IF NOT EXISTS sample;
            END
            $$;
            """
        );

        var script = migration.GetIdempotentScript();

        Assert.Contains("RAISE NOTICE 'Running migration", script);
        Assert.DoesNotContain("RAISE NOTICE 'Inserting record for migration", script);
        Assert.True(
            script.IndexOf("CREATE SCHEMA IF NOT EXISTS sample", StringComparison.Ordinal)
                < script.IndexOf("RAISE NOTICE 'Running migration", StringComparison.Ordinal)
        );
    }

    [Fact]
    public void LeadingSchemaCreationBlockKeepsRemainingStatementsIdempotent()
    {
        var migration = CreateMigration(
            """
            -- Generated by Sable
            -- Sable NoIdempotenceWrapper

            DO $$
            BEGIN
                CREATE SCHEMA IF NOT EXISTS sample;
            END
            $$;

            CREATE INDEX sample_index ON sample.items (id);
            """
        );

        var script = migration.GetIdempotentScript();

        Assert.Contains("RAISE NOTICE 'Running migration", script);
        Assert.True(
            script.IndexOf("RAISE NOTICE 'Running migration", StringComparison.Ordinal)
                < script.IndexOf("CREATE INDEX sample_index", StringComparison.Ordinal)
        );
    }

    [Fact]
    public void OrdinaryMigrationRemainsInsideIdempotenceBlock()
    {
        var migration = CreateMigration("CREATE TABLE sample.items (id uuid PRIMARY KEY);");

        var script = migration.GetIdempotentScript();

        Assert.Contains("DO $sable$", script);
        Assert.Contains("RAISE NOTICE 'Running migration", script);
        Assert.DoesNotContain("RAISE NOTICE 'Inserting record for migration", script);
    }

    [Fact]
    public void SplitLeadingSchemaCreationBlockSkipsCommentsAndWhitespace()
    {
        var script = """

            -- Generated by Sable
            DO $migration$
            BEGIN
                NULL;
            END
            $migration$;
            """;

        Assert.True(
            Migration.TrySplitLeadingSchemaCreationBlock(
                script.Replace("NULL;", "CREATE SCHEMA IF NOT EXISTS sample;"),
                out var schemaCreationBlock,
                out var remainingScript
            )
        );
        Assert.Contains("DO $migration$", schemaCreationBlock);
        Assert.True(string.IsNullOrWhiteSpace(remainingScript));
    }

    public void Dispose()
    {
        if (Directory.Exists(_directory))
        {
            Directory.Delete(_directory, true);
        }
    }

    private Migration CreateMigration(string script)
    {
        Directory.CreateDirectory(_directory);
        var filePath = Path.Combine(_directory, "20260710000000_Test.sql");
        File.WriteAllText(filePath, script);
        return new Migration(filePath, "sample");
    }
}
