// Copyright 2024 Bloomberg Finance L.P.
// Distributed under the terms of the MIT license.

using DotNet.Testcontainers.Builders;
using Npgsql;
using Xunit;

namespace Sable.Cli.Tests;

public class SafeSchemaPreamblePostgresSmokeTests
{
    private const string SmokeEnvironmentVariable = "SABLE_RUN_POSTGRES_SMOKE";
    private const string SchemaName = "sable_preamble_smoke";
    private const string MigrationId = "20260710000001_SafePreamble";

    [PostgresSmokeFact]
    [Trait("Category", "PostgresSmoke")]
    public async Task ConsolidatedMigrationReplaysTwiceInDisposablePostgres()
    {
        var databaseName = $"sable_smoke_{Guid.NewGuid():N}";
        var password = Guid.NewGuid().ToString("N");
        await using var container = new ContainerBuilder("postgres:15.1")
            .WithEnvironment("POSTGRES_DB", databaseName)
            .WithEnvironment("POSTGRES_USER", "postgres")
            .WithEnvironment("POSTGRES_PASSWORD", password)
            .WithPortBinding(5432, true)
            .WithWaitStrategy(Wait.ForUnixContainer().UntilInternalTcpPortIsAvailable(5432))
            .WithCleanUp(true)
            .Build();

        var projectDirectory = CreateMigrationProject();
        try
        {
            await container.StartAsync();
            var connectionString =
                $"Host=localhost;Port={container.GetMappedPublicPort(5432)};Username=postgres;Password={password};Database={databaseName};Pooling=false";
            await WaitUntilReady(connectionString);

            var manager = new MartenMigrationManager(new NullConsoleLogger());
            var script = await manager.CreateMigrationScript(
                Path.Combine(projectDirectory, "Smoke.csproj"),
                "Test"
            );

            await using var dataSource = NpgsqlDataSource.Create(connectionString);
            await Execute(dataSource, script);
            await Execute(dataSource, script);

            Assert.Equal(42, await Query<int>(dataSource, $"SELECT {SchemaName}.answer();"));
            Assert.Equal(
                "items",
                await Query<string>(
                    dataSource,
                    $"SELECT table_name FROM information_schema.tables WHERE table_schema = '{SchemaName}' AND table_name = 'items';"
                )
            );
            Assert.Equal(
                1L,
                await Query<long>(
                    dataSource,
                    $"SELECT count(*) FROM {SchemaName}.__sable_migrations WHERE migration_id = '{MigrationId}';"
                )
            );
        }
        finally
        {
            Directory.Delete(projectDirectory, true);
        }
    }

    private static string CreateMigrationProject()
    {
        var projectDirectory = Path.Combine(
            Path.GetTempPath(),
            $"sable-postgres-smoke-{Guid.NewGuid():N}"
        );
        var databaseDirectory = Path.Combine(projectDirectory, "sable", "Test");
        var migrationsDirectory = Path.Combine(databaseDirectory, "migrations");
        Directory.CreateDirectory(migrationsDirectory);
        File.WriteAllText(
            Path.Combine(projectDirectory, "Smoke.csproj"),
            "<Project Sdk=\"Microsoft.NET.Sdk\" />"
        );
        File.WriteAllText(Path.Combine(databaseDirectory, "schema.txt"), SchemaName);
        File.WriteAllText(
            Path.Combine(migrationsDirectory, "20260710000000_InfrastructureSetup.sql"),
            $$"""
            -- Generated by Sable
            -- Sable NoIdempotenceWrapper

            CREATE SCHEMA IF NOT EXISTS {{SchemaName}};

            CREATE TABLE IF NOT EXISTS {{SchemaName}}.__sable_migrations (
                migration_id character varying(150) NOT NULL,
                date_applied timestamp without time zone NOT NULL DEFAULT (now() at time zone 'utc'),
                backfilled boolean NOT NULL DEFAULT false,
                CONSTRAINT pkey___sable_migrations_migration_id PRIMARY KEY (migration_id)
            );
            """
        );
        File.WriteAllText(
            Path.Combine(migrationsDirectory, $"{MigrationId}.sql"),
            $$"""
            -- Generated by Sable

            DO $do$
            BEGIN
                BEGIN
                    EXECUTE 'CREATE SCHEMA IF NOT EXISTS {{SchemaName}}';
                EXCEPTION
                    WHEN duplicate_schema THEN NULL;
                    WHEN unique_violation THEN NULL;
                END;
            END
            $do$;

            CREATE TABLE {{SchemaName}}.items (id integer PRIMARY KEY);

            CREATE OR REPLACE FUNCTION {{SchemaName}}.answer() RETURNS integer
            LANGUAGE sql
            AS $$
                SELECT 42;
            $$;
            """
        );

        return projectDirectory;
    }

    private static async Task WaitUntilReady(string connectionString)
    {
        using var timeout = new CancellationTokenSource(TimeSpan.FromSeconds(30));
        while (true)
        {
            try
            {
                await using var connection = new NpgsqlConnection(connectionString);
                await connection.OpenAsync(timeout.Token);
                return;
            }
            catch (Exception) when (!timeout.IsCancellationRequested)
            {
                await Task.Delay(TimeSpan.FromMilliseconds(250), timeout.Token);
            }
        }
    }

    private static async Task Execute(NpgsqlDataSource dataSource, string script)
    {
        await using var command = dataSource.CreateCommand(script);
        await command.ExecuteNonQueryAsync();
    }

    private static async Task<T> Query<T>(NpgsqlDataSource dataSource, string sql)
    {
        await using var command = dataSource.CreateCommand(sql);
        return (T)(await command.ExecuteScalarAsync())!;
    }

    private sealed class NullConsoleLogger : IConsoleLogger
    {
        public void LogInfo(string message) { }

        public void LogError(string message) { }
    }

    private sealed class PostgresSmokeFactAttribute : FactAttribute
    {
        public PostgresSmokeFactAttribute()
        {
            if (!string.Equals(Environment.GetEnvironmentVariable(SmokeEnvironmentVariable), "1"))
            {
                Skip = $"Set {SmokeEnvironmentVariable}=1 to run the disposable PostgreSQL smoke test.";
            }
        }
    }
}
